version: "3.7"
services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  superset:
    env_file:
      - dev.env
    build: .
    container_name: superset_app
    ports:
      - 8083:8088
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4",
        ]

volumes:
  superset_home:
    external: false
  redis:
    external: false