ARG VERSION=v0.10.2
FROM linkedin/datahub-gms:${VERSION}

ENV DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID=generic-duhe-consumer-job-client-gms
ENV ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
ENV ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
ENV ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
ENV ENTITY_SERVICE_ENABLE_RETENTION=true
ENV ES_BULK_REFRESH_POLICY=WAIT_UNTIL
ENV GRAPH_SERVICE_DIFF_MODE_ENABLED=true
ENV GRAPH_SERVICE_IMPL=elasticsearch
ENV JAVA_OPTS="-Xms1g -Xmx1g"
ENV MAE_CONSUMER_ENABLED=true
ENV MCE_CONSUMER_ENABLED=true
ENV PE_CONSUMER_ENABLED=true
ENV UI_INGESTION_ENABLED=true
ENV METADATA_SERVICE_AUTH_ENABLED=true