ARG VERSION=v0.10.2
FROM linkedin/datahub-frontend-react:${VERSION}

ENV DATAHUB_APP_VERSION=1.0
ENV DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
ENV JAVA_OPTS="-Xms512m -Xmx512m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null"

ENV DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
ENV METADATA_SERVICE_AUTH_ENABLED=true