[sources.nginx_logs]
  type = "file"
  include = ["/var/log/nginx/access.log"]
  start_at_beginning = false

[sinks.kafka_logs]
  type = "kafka"
  inputs = ["nginx_logs"]
  bootstrap_servers = "kafka:9092"
  topic = "ad_action_event_log"