version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - '8443:8443'
    environment:
      - NIFI_WEB_PROXY_HOST=192.168.5.115:8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456admin.
    volumes:
      - ./data:/opt/nifi/nifi-current/data